<a href="https://colab.research.google.com/github/ishwarvenugopal/CE888_Data_Science_and_Decision_Making/blob/master/Lab_1/Lab_1_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Create a (4 x 2) integer array and print it's attributes

In [2]:
import numpy as np
a = np.array([[ 0, 1],
              [10,11],
              [20,21],
              [30,31]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[ 0  1]
 [10 11]
 [20 21]
 [30 31]]
(4, 2)
8
2


## 2.Create an array of dimension (1,10) and sort it in ascending and descending order

In [13]:
b=np.array([1,5,2,6,3,7,4,10,9,8])
print(b)
sorted_array=np.sort(b)
print(sorted_array)
reverse_array = sorted_array[::-1]
print(reverse_array)

[ 1  5  2  6  3  7  4 10  9  8]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


## 3.Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [22]:
c=np.array([1,2,3,4,5,6,7,8,9])
print(c)
new_array = np.reshape(c, (3,3))
print(new_array)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 4.Stack two arrays of any size horizontally and vertically

In [31]:
a1=np.array([[1,2],[3,4]])
print(a1)
a2=np.array([[6,7],[8,9]])
print(a2)
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[1 2 6 7]
 [3 4 8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]


## 5.Create two array of same size and find commom elements

In [34]:
a1=np.array([1,2,3,4])
print(a1)
a2=np.array([6,7,4,9])
print(a2)
common_elements = np.intersect1d(a1,a2)
print(common_elements)

[1 2 3 4]
[6 7 4 9]
[4]


## 6.Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [41]:
a6=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])
print(a6)
i=1
for row in a6:
  print("Row: ",i,", Min: ",min(row),", Max: ",max(row))
  i+=1
i=1
for column in a6.T:
  print("Column: ",i,", Min: ",min(column),", Max: ",max(column))
  i+=1

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
Row:  1 , Min:  1 , Max:  5
Row:  2 , Min:  11 , Max:  15
Row:  3 , Min:  21 , Max:  25
Row:  4 , Min:  31 , Max:  35
Row:  5 , Min:  41 , Max:  45
Column:  1 , Min:  1 , Max:  41
Column:  2 , Min:  2 , Max:  42
Column:  3 , Min:  3 , Max:  43
Column:  4 , Min:  4 , Max:  44
Column:  5 , Min:  5 , Max:  45


## 7.Create an array of size 100 and compute the mean, median, standard deviation.

In [44]:
a7=np.arange(100)
print(a7)
print("Mean: ",np.mean(a7))
print("Median: ",np.median(a7))
print("Standard Deviation :",np.std(a7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Mean:  49.5
Median:  49.5
Standard Deviation : 28.86607004772212


## 8. Normalize a 5x5 random matrix

In [50]:
a8=np.random.rand(5,5)
print(a8)
a8=(a8-np.min(a8))/(np.max(a8)-np.min(a8))
print("Normalised matrix: ")
print(a8)


[[0.58290268 0.66967359 0.43581908 0.1881975  0.00927866]
 [0.57534234 0.99787183 0.823509   0.25205166 0.15080324]
 [0.94149695 0.66402503 0.7257422  0.28982795 0.67826286]
 [0.02242967 0.87348832 0.88433025 0.20331203 0.8870356 ]
 [0.21334159 0.68280076 0.80945073 0.07184229 0.37177646]]
Normalised matrix: 
[[0.58024275 0.66801486 0.43146204 0.18098329 0.        ]
 [0.57259518 1.         0.8236253  0.24557422 0.14315755]
 [0.94297465 0.66230113 0.72473041 0.2837864  0.67670324]
 [0.01330275 0.87418129 0.88514833 0.19627222 0.88788489]
 [0.2064175  0.6812935  0.80940482 0.06328552 0.36668046]]


## 9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [58]:
a9_1=np.random.random((4,4,3))
print(a9_1)
a9_2=np.random.random((4,4))
print(a9_2)

print("Multiplied product:")
np.outer(a9_1,a9_2)

[[[0.13507523 0.35213716 0.02831698]
  [0.7674567  0.4991983  0.17423656]
  [0.25058551 0.78024558 0.71382304]
  [0.5878306  0.74745383 0.29590585]]

 [[0.22256356 0.40306488 0.43475048]
  [0.98902249 0.40210849 0.21846892]
  [0.12479993 0.4394325  0.70400976]
  [0.53275084 0.11775834 0.09888898]]

 [[0.73827141 0.50010494 0.9721124 ]
  [0.29222158 0.95843977 0.21164136]
  [0.39349682 0.05560996 0.45212684]
  [0.238764   0.43666724 0.52497567]]

 [[0.19174365 0.78207484 0.38609924]
  [0.23209793 0.02481634 0.5467553 ]
  [0.09062342 0.62978712 0.51653914]
  [0.28017163 0.80474846 0.89521872]]]
[[0.25614492 0.598916   0.32328159 0.96886153]
 [0.87886633 0.09026919 0.13471673 0.72218655]
 [0.55861109 0.68228486 0.40127464 0.22282843]
 [0.63111208 0.92754619 0.73489805 0.44327517]]
Multiplied product:


array([[0.03459883, 0.08089872, 0.04366734, 0.13086919, 0.11871307,
        0.01219313, 0.01819689, 0.09754951, 0.07545452, 0.09215978,
        0.05420226, 0.0300986 , 0.08524761, 0.12528852, 0.09926652,
        0.0598755 ],
       [0.09019814, 0.21090058, 0.11383946, 0.34117215, 0.30948149,
        0.03178714, 0.04743877, 0.25430872, 0.19670772, 0.24025785,
        0.14130371, 0.07846617, 0.22223802, 0.32662348, 0.25878491,
        0.15609366],
       [0.00725325, 0.01695949, 0.00915436, 0.02743524, 0.02488684,
        0.00255615, 0.00381477, 0.02045014, 0.01581818, 0.01932025,
        0.01136289, 0.00630983, 0.01787119, 0.02626531, 0.0208101 ,
        0.01255222],
       [0.19658014, 0.4596421 , 0.24810463, 0.74355927, 0.67449186,
        0.0692777 , 0.10338925, 0.5542469 , 0.42870982, 0.52362409,
        0.30796091, 0.17101117, 0.4843512 , 0.71185154, 0.56400243,
        0.3401945 ],
       [0.12786711, 0.29897785, 0.16138162, 0.48365402, 0.43872857,
        0.04506223, 0.06725036, 