<a href="https://colab.research.google.com/github/ishwarvenugopal/CE888_Data_Science_and_Decision_Making/blob/master/Lab_1/Lab_1_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Create a (4 x 2) integer array and print it's attributes

In [2]:
import numpy as np
a = np.array([[ 0, 1],
              [10,11],
              [20,21],
              [30,31]])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)

[[ 0  1]
 [10 11]
 [20 21]
 [30 31]]
(4, 2)
8
2


## 2.Create an array of dimension (1,10) and sort it in ascending and descending order

In [13]:
b=np.array([1,5,2,6,3,7,4,10,9,8])
print(b)
sorted_array=np.sort(b)
print(sorted_array)
reverse_array = sorted_array[::-1]
print(reverse_array)

[ 1  5  2  6  3  7  4 10  9  8]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


## 3.Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [22]:
c=np.array([1,2,3,4,5,6,7,8,9])
print(c)
new_array = np.reshape(c, (3,3))
print(new_array)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 4.Stack two arrays of any size horizontally and vertically

In [31]:
a1=np.array([[1,2],[3,4]])
print(a1)
a2=np.array([[6,7],[8,9]])
print(a2)
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[1 2 6 7]
 [3 4 8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]


## 5.Create two array of same size and find commom elements

In [34]:
a1=np.array([1,2,3,4])
print(a1)
a2=np.array([6,7,4,9])
print(a2)
common_elements = np.intersect1d(a1,a2)
print(common_elements)

[1 2 3 4]
[6 7 4 9]
[4]


## 6.Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [41]:
a6=np.array([[1,2,3,4,5],[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35],[41,42,43,44,45]])
print(a6)
i=1
for row in a6:
  print("Row: ",i,", Min: ",min(row),", Max: ",max(row))
  i+=1
i=1
for column in a6.T:
  print("Column: ",i,", Min: ",min(column),", Max: ",max(column))
  i+=1

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]
Row:  1 , Min:  1 , Max:  5
Row:  2 , Min:  11 , Max:  15
Row:  3 , Min:  21 , Max:  25
Row:  4 , Min:  31 , Max:  35
Row:  5 , Min:  41 , Max:  45
Column:  1 , Min:  1 , Max:  41
Column:  2 , Min:  2 , Max:  42
Column:  3 , Min:  3 , Max:  43
Column:  4 , Min:  4 , Max:  44
Column:  5 , Min:  5 , Max:  45


## 7.Create an array of size 100 and compute the mean, median, standard deviation.

In [44]:
a7=np.arange(100)
print(a7)
print("Mean: ",np.mean(a7))
print("Median: ",np.median(a7))
print("Standard Deviation :",np.std(a7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Mean:  49.5
Median:  49.5
Standard Deviation : 28.86607004772212


## 8. Normalize a 5x5 random matrix

In [50]:
a8=np.random.rand(5,5)
print(a8)
a8=(a8-np.min(a8))/(np.max(a8)-np.min(a8))
print("Normalised matrix: ")
print(a8)


[[0.58290268 0.66967359 0.43581908 0.1881975  0.00927866]
 [0.57534234 0.99787183 0.823509   0.25205166 0.15080324]
 [0.94149695 0.66402503 0.7257422  0.28982795 0.67826286]
 [0.02242967 0.87348832 0.88433025 0.20331203 0.8870356 ]
 [0.21334159 0.68280076 0.80945073 0.07184229 0.37177646]]
Normalised matrix: 
[[0.58024275 0.66801486 0.43146204 0.18098329 0.        ]
 [0.57259518 1.         0.8236253  0.24557422 0.14315755]
 [0.94297465 0.66230113 0.72473041 0.2837864  0.67670324]
 [0.01330275 0.87418129 0.88514833 0.19627222 0.88788489]
 [0.2064175  0.6812935  0.80940482 0.06328552 0.36668046]]


## 9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [61]:
a9_1=np.random.random((4,4,3))
print(a9_1)
a9_2=np.random.random((4,4))
print(a9_2)

print("Multiplied product:")
a9_1 * a9_2[:,:,None]

[[[0.22866497 0.59752281 0.92929467]
  [0.96773869 0.19899165 0.64942993]
  [0.0755331  0.42709183 0.35692116]
  [0.75380525 0.48046316 0.71419353]]

 [[0.24320325 0.81404452 0.00721742]
  [0.52698082 0.46772192 0.66104083]
  [0.62809523 0.5453068  0.2772913 ]
  [0.10321265 0.84724269 0.96207521]]

 [[0.78484736 0.78275794 0.37621517]
  [0.24176381 0.53137143 0.40830737]
  [0.04094232 0.7940287  0.36586196]
  [0.0097044  0.30436062 0.90617644]]

 [[0.65109004 0.26506462 0.97461716]
  [0.63966689 0.36654694 0.34509984]
  [0.90417477 0.30399235 0.90760534]
  [0.12744785 0.2311165  0.47894535]]]
[[0.49442597 0.680115   0.6400935  0.47694032]
 [0.3776834  0.42742559 0.4922067  0.98636848]
 [0.00601812 0.96604126 0.34033905 0.56391719]
 [0.43384454 0.54942003 0.00494737 0.23986346]]
Multiplied product:


array([[[0.1130579 , 0.2954308 , 0.45946742],
        [0.6581736 , 0.13533721, 0.44168703],
        [0.04834825, 0.2733787 , 0.22846291],
        [0.35952011, 0.22915225, 0.34062769]],

       [[0.09185383, 0.3074511 , 0.0027259 ],
        [0.22524509, 0.19991632, 0.28254577],
        [0.30915268, 0.26840366, 0.13648464],
        [0.1018057 , 0.83569349, 0.94896066]],

       [[0.0047233 , 0.00471073, 0.00226411],
        [0.23355381, 0.51332672, 0.39444176],
        [0.01393427, 0.27023897, 0.12451711],
        [0.00547248, 0.17163419, 0.51100847]],

       [[0.28247186, 0.11499684, 0.42283234],
        [0.3514458 , 0.20138823, 0.18960477],
        [0.00447329, 0.00150396, 0.00449026],
        [0.03057008, 0.0554364 , 0.11488149]]])